# Generated by Django 2.0.2 on 2018-02-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20180219_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timeNeeded',
            field=models.IntegerField(choices=[(1, 'Many hours'), (2, 'Up to several hours'), (3, '<1 hour')], default=2),
        ),
    ]
