# Generated by Django 2.0.2 on 2018-02-20 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_timeneeded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priority',
            new_name='importance',
        ),
    ]
