# Generated by Django 2.0.2 on 2018-02-20 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20180220_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='timeNeeded',
            new_name='durations',
        ),
    ]
