# Generated by Django 2.0.2 on 2018-02-19 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20180216_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descr',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='task',
            name='dateAdded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Now'), (2, 'Soon'), (3, 'Eventually')], default=3),
        ),
    ]
