# Generated by Django 2.0.2 on 2018-03-11 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0007_auto_20180220_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.IntegerField(choices=[(12, 'Many hours'), (5, 'Up to several hours'), (1, '<1 hour')], default=5, help_text='How long will it take?'),
        ),
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.IntegerField(choices=[(3, 'Now'), (2, 'Soon'), (1, 'Eventually')], default=1, help_text='When do you gotta get this done?'),
        ),
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
