# Generated by Django 2.0.2 on 2018-05-24 01:42

import datetime
from django.db import migrations, models
import django.db.models.expressions
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20180311_0318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['done', django.db.models.expressions.OrderBy(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('importance'), '*', django.db.models.expressions.CombinedExpression(django.db.models.expressions.Value(datetime.datetime(2018, 5, 24, 1, 42, 54, 877542, tzinfo=utc)), '-', django.db.models.expressions.F('dateAdded'))), '+', django.db.models.expressions.CombinedExpression(django.db.models.expressions.DurationValue(datetime.timedelta(0, 3600), output_field=models.DurationField()), '*', django.db.models.expressions.F('duration'))), descending=True)]},
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.IntegerField(choices=[(3, 'Many hours'), (2, 'Up to several hours'), (1, 'Less than 1 hour')], default=2, help_text='How long will it take?'),
        ),
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.IntegerField(choices=[(3, 'Now'), (2, 'Soon'), (1, 'Eventually')], default=1, help_text='When do you have to do it?'),
        ),
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True, help_text='Add anything related to this task here', max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='What do you have to get done?', max_length=100),
        ),
    ]
