# Generated by Django 2.0.2 on 2018-05-29 06:14

import datetime
from django.db import migrations, models
import django.db.models.expressions
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20180529_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['done', django.db.models.expressions.OrderBy(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('importance'), '*', django.db.models.expressions.CombinedExpression(django.db.models.expressions.Value(datetime.datetime(2018, 5, 29, 6, 13, 58, 656292, tzinfo=utc)), '-', django.db.models.expressions.F('dateAdded'))), '+', django.db.models.expressions.CombinedExpression(django.db.models.expressions.DurationValue(datetime.timedelta(0, 3600), output_field=models.DurationField()), '*', django.db.models.expressions.F('duration'))), descending=True)]},
        ),
    ]
